---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: restapi-frontend
          image: 892958774317.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "lesson4"
            - name: POSTGRES_HOST
              value: "database-3.cwd19revbd1j.us-east-1.rds.amazonaws.com"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_PROFILE
              value: "default"
            - name: AWS_BUCKET
              value: "test-ff1732da23c2-dev"
            - name: JWT_SECRET
              value: "testing"
            - name: AWS_ACCESS_KEY_ID
              value: "ASIA472D5SQW6QPIMQ5G"
            - name: AWS_SECRET_ACCESS_KEY
              value: "3I2wVf5Y+9QgLaOC744ClbdWO9Q3tubvv+2KKOnh"
            - name: AWS_SESSION_TOKEN
              value: "FwoGZXIvYXdzEKn//////////wEaDAkgbsqXV9mCCrS9FCLVATsn1K/pT8np+aPU78vxR8vfpJK89OHqjhO9gFRkOKjwCPv26uV/mNsm6122U7ba8RY5XaucpXjVL/wQ3uuAoPjX0tXxgeXkoQT3VSIzY68YK4VuoELf4twtWS0zdSnE+nyxBoXy7S49ytOjp9Pe5hOwjPAXqilZE05rynrBiKLxM6fPefuxZvHKA1DZr56vacNTiqIJxHz0HQRNBp439shGWSJU7dno/o4cJQI2UgO3XuF3ylx2GRqcYa2YbBYhA1Rdg7oUoTRqHt8ra+joiJtcI4d0MyjG0OCnBjItPWHSuhB9CV/0JA9b22HsX1NhD7aWf4TxgMc1WQL7VbsXe+lgOnd9KRSrLq5G"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  labels:
    run: frontend-app
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: frontend-app
